apiVersion: v1
kind: Service
metadata:
  name: boutique-simple-lb
  namespace: online-boutique
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: boutique-coordinator
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
